# Generated by Django 3.2 on 2021-04-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juke', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.TextField(max_length=100),
        ),
    ]
