# Generated by Django 3.2 on 2021-04-23 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juke', '0005_auto_20210423_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.DateTimeField(auto_now_add=True)),
                ('follower_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_article_set', to=settings.AUTH_USER_MODEL)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_article_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
